### ISSUE TITLE
Can it be made compatible with vim versions prior to 8

### ISSUE THREAD

**Issue by marcink** [rickhowe/spotdiff.vim#2]
I install Vim 8 on any machine I can.  Some are controlled by company IT and only come with Vim 7.  Is there any way to having this plugin work in Vim 7?

**Comment by rickhowe** [comment]
Thanks for using and asking, but I have no plan to go back to more than 5 years ago.

**Comment by marcink** [comment]
Was there a version in the past that worked with Vim 7?

A lot of hardware development is done on older Linux distributions (like CentOS7) that only comes with Vim 7, and the Linux machines often lack the packages required to build a local install of Vim 8 (I tried).

Thank you for taking the time to respond.

**Comment by rickhowe** [comment]
You can see the version history on:
https://www.vim.org/scripts/script.php?script_id=5509

If you would also be interested in diffchar.vim, check:
https://www.vim.org/scripts/script.php?script_id=4932

**Comment by marcink** [comment]
Thanks @rickhowe, this was just the information to find version that works with vim prior to 8.  I ended up installing diffchar as a standard plugin.  RE spotdiff, I am using linediff for now, but keeping an eye on your spotdiff.   Thank you.
