### ISSUE TITLE
Suggestion: Vertical Layout

### ISSUE THREAD

**Issue by vds2212** [rickhowe/spotdiff.vim#3]
When comparing two sections in the same buffer the plugin create a window below the original buffer.

When comparing two files it is sometime easier to have the windows side by side.
It would be good to have an option to drive the plugin the put the windows side by side.

![image](https://github.com/rickhowe/spotdiff.vim/assets/160393/e1ace988-56de-461c-868e-5477ecb2ca9d)

**Comment by rickhowe** [comment]
The vertical split is an idea to keep the arrangement (layout/size/position) of other windows in the tab page. Actually the original + new windows should look the original one (with same height and width). It is difficult for a plugin to decide which side-by-side arrangement would be reasonable. But a user can move it as he/she want.

**Comment by vds2212** [comment]
Indeed but à setting to let the user choose would be nice at least to me ;-)

**Comment by rickhowe** [comment]
OK, let me try.

**Comment by rickhowe** [comment]
Now you can try it on update 5.1 if  `"vertical"` is included in the `diffopt` option.

**Comment by vds2212** [comment]
Great, I'm in a business trip and I can't test now. I'll test as soon as possible :-)
Thanks for your support and the great plugin you wrote :-)

**Comment by vds2212** [comment]
It works like a charm :-)

Thank you very much!

**Comment by rickhowe** [comment]
FYI: If you prefer side-by-side diff view, [wrapfiller](https://github.com/rickhowe/wrapfiller) plugin might help you.

**Comment by vds2212** [comment]
Thanks for the recommendation :-) I will test it.
